"""Add order tracking fields and status history table

Revision ID: 0e7dbc41d878
Revises: 8a9c30284425
Create Date: 2026-02-01 11:14:32.107298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7dbc41d878'
down_revision: Union[str, None] = '8a9c30284425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('carrier_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'estimated_delivery_date')
    op.drop_column('orders', 'carrier_name')
    # ### end Alembic commands ###
