"""Add coupons and coupon_usage tables, add coupon_code to orders

Revision ID: 8a9c30284425
Revises: 6e76dabaa759
Create Date: 2026-02-01 11:04:13.356152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9c30284425'
down_revision: Union[str, None] = '6e76dabaa759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('coupon_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'coupon_code')
    # ### end Alembic commands ###
