"""Add reviews table and product rating fields

Revision ID: 8eb6baf3a74f
Revises: 3c42e0f37f59
Create Date: 2026-02-01 10:55:54.558943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb6baf3a74f'
down_revision: Union[str, None] = '3c42e0f37f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('avg_rating', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('review_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'avg_rating')
    # ### end Alembic commands ###
